# Generated by Django 5.2.6 on 2025-09-27 17:09

import product.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/', validators=[product.validators.validate_file_size]),
        ),
    ]
